### ISSUE TITLE
ReadMe update

### ISSUE THREAD

**Issue by OgLocGreen** [Rhythmblue/i3d_finetune#1]
Hey, are still working on this Project? Will there be an update for the ReadMe?

**Comment by panna19951227** [comment]
I am running python train.py ucf101 rgb,but I can not succeed running,Can you update your ReadMe?Thanks!

**Comment by Rhythmblue** [comment]
So sorry！I am too busy with my lessons.
Here is a new repo created by my colleagues and me.

https://github.com/USTC-Video-Understanding/I3D_Finetune
