### ISSUE TITLE
有关RGB提取的问题

### ISSUE THREAD

**Issue by TaoXieSZ** [Rhythmblue/i3d_finetune#3]
你好！

我想请问一下：

1、提取RGB的操作是将每段视频的所有帧提取吗？
2、如果我已经有了所有帧的数据，但是文件名不是frameXXXXX.jpg，因此出现路径无法找到的问题，那么代码中哪里能修改所需要读取的文件名呢？

谢谢！

**Comment by Rhythmblue** [comment]
你可以把这边的改掉
https://github.com/Rhythmblue/i3d_finetune/blob/25c75e906663cc859d2b36871ab8d3f6b878df7c/rmb_lib/video_3d.py#L9

**Comment by TaoXieSZ** [comment]
> 你可以把这边的改掉
> [i3d_finetune/rmb_lib/video_3d.py](https://github.com/Rhythmblue/i3d_finetune/blob/25c75e906663cc859d2b36871ab8d3f6b878df7c/rmb_lib/video_3d.py#L9)
> 
> Line 9 in [25c75e9](/Rhythmblue/i3d_finetune/commit/25c75e906663cc859d2b36871ab8d3f6b878df7c)
> 
>  def __init__(self, info_list, tag='rgb', img_format='frame{:06d}{}.jpg'):

前几天也找到了，解决了问题，谢谢！
PS：师姐头像真好看呀~
